name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            sudo chown -R $USER:$USER /commitbody/commitbody-front
            sudo chmod -R u+rw /commitbody/commitbody-front/.git

            cd /commitbody/commitbody-front
            rm -f .git/index.lock
            git fetch --all
            git reset --hard origin/main
            git pull origin main || echo "Git pull failed"

            cd /commitbody
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose -f docker-compose.blue.yml up -d --build --no-cache
