name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3\

      - name: env setting
        run: |
          echo "${{secrets.ENV}}" > .env
          echo "created env."

      - name: env file
        run: cat .env

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
#          script: |
#            cd /docker/front
#            ./deploy.sh
