name: Deploy Frontend

on:
  push:
    branches:
      - CD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd /docker/front/commitbody-front
            git pull origin CD
            sudo docker rmi commitbody-commit_front_api || true
            sudo docker stop commit-front || true
            sudo docker rm commit-front || true
            sudo docker-compose -f docker-compose.front.yml -p commit-front up -d
